on:
  push:
    branches:
    - master

name: Master branch CI

jobs:
  jekyll-latest:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build Jekyll site
      uses: fabacab/jekyll-builder-for-github-pages-action@v1
      with:
        pre_build_commands: gem install bundler
        secret_gh_pages_api_token: ${{ secrets.API_TOKEN_GITHUB }}
        gh_pages_publishing_source: gh-pages
