on:
  push:
    branches:
    - master

name: Master branch CI

jobs:
  jekyll-latest:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build Jekyll site
      uses: fabacab/jekyll-builder-for-github-pages-action@v1
      with:
        pre_build_commands: gem install bundler

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: _site